Tienda_Online/hakunamatata/carroapp/urls.py
from django.urls import path
from . import views


app_name="carro"


urlpatterns = [
    
    path("agregar/<int:producto_id>/", views.agregar_producto, name="agregar"),
    path("eliminar/<int:producto_id>/", views.eliminar_producto, name="eliminar"),
    path("restar/<int:producto_id>/", views.restar_producto, name="restar"),
    path("limpiar/", views.limpiar_carro, name="limpiar"),
    
]

Tienda_Online/hakunamatata/hakunamatata/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('hakunamatataapp.urls')),
    path('servicios/', include('serviciosapp.urls')),
    path('noticias/', include('noticiasapp.urls')),
    path('contacto/', include('contactoapp.urls')),
    path('tienda/', include('tiendaapp.urls')),
    path('carro/', include('carroapp.urls')),
    path('autenticacion/', include('autenticacionapp.urls')),
    path('pedidos/', include('pedidosapp.urls')),
]

Tienda_Online/hakunamatata/tiendaapp/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.Tienda, name="Tienda"),
    
]

Tienda_Online/hakunamatata/tiendaapp/models.py
from distutils.command.upload import upload
from mailbox import NoSuchMailboxError
from tabnanny import verbose
from turtle import update
from django.db import models

# Create your models here.
class CatergoriaProd(models.Model):
    nombre=models.CharField(max_length=50)
    created=models.DateTimeField(auto_now_add=True)
    update=models.DateTimeField(auto_now_add=True)
    
    class Meta:
        verbose_name="categoriaprod"
        verbose_name_plural="categoriasprods"
        
    def __str__(self):
        return self.nombre
    
class Producto(models.Model):
    nombre=models.CharField(max_length=50)
    categorias=models.ForeignKey(CatergoriaProd, on_delete=models.CASCADE)
    imagen=models.ImageField(upload_to="tienda", null=True, blank=True)
    precio=models.FloatField()
    stock=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    update=models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.nombre
    
    class Meta:
        verbose_name="producto"
        verbose_name_plural="productos"
    

Tienda_Online/hakunamatata/tiendaapp/views.py
from django.shortcuts import render
from .models import Producto

# Create your views here.


def Tienda(request):
    
    productos=Producto.objects.all()
    
    return render(request,"tiendaapp/tienda.html", {"productos":productos})

Tienda_Online/hakunamatata/tiendaapp/templates/tiendaapp/carro/widget.html
    
    <table class="table table-bordered" style="color: black">
        <thead>
            <tr>
                <th>Producto</th>
                <th>Suma</th>
            </tr>
        </thead>
        <tbody>
            {% if request.session.carro.items %}
                {% for key, value in request.session.carro.items %}

                    <tr class="text-center">
                        <td>{{value.nombre}}</td>
                        <td>
                            {{value.cantidad}}
                            <a href="{% url 'carro:agregar' value.producto_id %}" class="btn btn-success">+</a>
                            <a href="{% url 'carro:restar' value.producto_id %}" class="btn btn-success">-</a><br/>
                            $ {{value.precio}}
                        </td>
                    </tr>
                {% endfor %}
            {% else%}
                <tr>
                    <td colspan="3">
                        <div class="alert alert-danger text-center">
                            Sin Productos
                        </div>
                    </td>
                </tr>
            {% endif %}
        </tbody>
        <tfoot>
            <tr>
                <td colspan="3" style="text-align: center;">
                    Total: $ {{importe_total_carro}}
                </td>
            </tr>
            {% if request.session.carro.items %}
            <tr>
                <td colspan="3" style="text-align: center;">
                    <a href="{% url 'procesar_pedido' %}" class="btn btn-success" >Hacer Compra</a>
                </td>
            </tr>
            {% endif %}

            
        </tfoot>

        

    </table>